## Numpy array and basic

In [1]:
import numpy as np

## creating array from list

In [2]:
arr_1d = np.array([1,2,3,4])
print("1D array:", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array:", arr_2d)

1D array: [1 2 3 4]
2D array: [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [3]:
py_list = [1,2,3]
print(py_list,"python list ")

[1, 2, 3] python list 


In [4]:
np_array = np.array([1,2,3]) # element wise multiplication
print("Python list multliplication", np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n list operation time", time.time() - start)

start = time.time()
np_array = np.arange(1000000)*2
print("\n Numpy list operation time", time.time() - start)

Python list multliplication [2 4 6]

 list operation time 0.11373448371887207

 Numpy list operation time 0.007324934005737305


### creating array from scratch

In [5]:
zeros = np.zeros((3,4))
print("\n zeros array", zeros)

ones = np.ones((2,3))
print("one array: \n", ones)

full = np.full((2,2), 7)
print("full array: \n", full)


random = np.random.random((2,3))
print("random array: \n", random)

sequence = np.arange(0,11, 2)
print("sequence array: \n", sequence)


 zeros array [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.97538363 0.28248622 0.24992924]
 [0.67467298 0.0662101  0.0853194 ]]
sequence array: 
 [ 0  2  4  6  8 10]


### vector, matrix and tensor

vector = np.array([1,2,3])
print("vector: ", vector)

matrix = np.array([[1,2,3], [4,5,6]])
print("matrix: ", matrix)

tensor = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print("tensor: \n", tensor)

### array properties

In [10]:
arr = np.array([[1,2,3], [4,5,6]])
print("shape of array:", arr.shape)
print("dimesion", arr.ndim)
print("size", arr.size)
print("datatype", arr.dtype)

shape of array: (2, 3)
dimesion 2
size 6
datatype int64


### Array Re-shapping

In [18]:
arr = np.arange(12)
print("original", arr)

reshaped = arr.reshape((3,4))
print("\n reshaped array", reshaped)

flattened = reshaped.flatten()
print("flattened", flattened)

# ravel (return view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array", raveled)

# Transpose 
transpose = reshaped.T
print("\n Transpose array", transpose)

original [ 0  1  2  3  4  5  6  7  8  9 10 11]

 reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


# Phase 2 of Numpy libraries learning