### Numpy Array Operations

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing", arr[2:7])
print("with step", arr[1:8:2])
print("negative indexing", arr[-3])

Basic slicing [3 4 5 6 7]
with step [2 4 6 8]
negative indexing 8


In [7]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Specific element", arr_2d[1,2])
print("Entire row:", arr_2d[1])
print("Entire row:", arr_2d[:, 1])

Specific element 6
Entire row: [4 5 6]
Entire row: [2 5 8]


### Sorting 

In [12]:
unsorted = np.array([1,4,6,5,2,7,8,9,4,6,2,3,6,1,7])
print("sorted array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1], [1,2], [2,3]])
print("sorted 2d array by column ", np.sort(arr_2d_unsorted, axis=0))


sorted array [1 1 2 2 3 4 4 5 6 6 6 7 7 8 9]
sorted 2d array by column  [[1 1]
 [2 2]
 [3 3]]


## Filters

In [13]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


## Filter with mask

In [14]:
mask = numbers>5
print("Numbers greater than 5", numbers[mask])

Numbers greater than 5 [ 6  7  8  9 10]


## fancy indexing vs np.where()

In [16]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers>5)
print(where_result)
print("NP where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [21]:
condition_array = np.where(numbers>5, "true","false")
print("conditions array", condition_array)

conditions array ['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and removing data

In [25]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


### array compartibility

In [27]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([7,8,9])

print("compatibility shapes", a.shape == b.shape)

compatibility shapes False


In [33]:
original = np.array([[1,2],[3,4],])
new_row = np.array([[5,6]])

with_new_row = np.vstack((orginal, new_row))
print(original)
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("with new column", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
with new column [[1 2 7]
 [3 4 8]]


### Delete Operations

In [36]:
arr = np.array([1,2,3,4,5,6])
deleted = np.delete(arr, 2)
print("Array after deletion",deleted)

Array after deletion [1 2 4 5 6]
